import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    GridLayout {
        padding: 50px;
        spacing: 25px;
        
        Row {
            Text {
                x:0;y:0;
                text: "Enter Total Income";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
                color: black;
            }
        }
        Row{
            LineEdit {
                font-size: 16px;
                placeholder-text: "Enter your number";
            }
        }
        Row{

            Button {
                text: "Calculate";
                clicked => { self.text = "Calculating..."; }
            }
        }

    }   

}
